### ISSUE TITLE
error running first prisma deploy

### ISSUE THREAD

**Issue by kokokenada** [prisma/datamodel-v1.1-feedback#11]
after correcting the various compile errors, I run prisma deploy and get
````
Applying changes... (56/64)  client Sending query to cluster local +505ms
  client http://localhost:4467/management +0ms
  client query ($name: String! $stage: String!) {
  client           migrationStatus(name: $name stage: $stage) {
  client             projectId
  client             revision
  client             status
  client             applied
  client             rolledBack
  client             errors
  client           }
  client         }
  client        +0ms
  client { stage: 'default', name: 'ahr-server' } +0ms
  client { migrationStatus:
  client    { rolledBack: 41,
  client      applied: 60,
  client      projectId: 'ahr-server$default',
  client      errors:
  client       [ 'java.lang.RuntimeException: MigrationValue method should only be called on scalar fields.\n\tat scala.sys.package$.error(package.scala:26)\n\tat com.prisma.deploy.connector.MigrationValueGenerator.migrationValueForField(MigrationValueGenerator.scala:18)\n\tat com.prisma.deploy.connector.MigrationValueGenerator.migrationValueForField$(MigrationValueGenerator.scala:9)\n\tat com.prisma.deploy.connector.postgres.database.PostgresJdbcDeployDatabaseMutationBuilder.migrationValueForField(PostgresJdbcDeployDatabaseMutationBuilder.scala:20)\n\tat com.prisma.deploy.connector.postgres.database.PostgresJdbcDeployDatabaseMutationBuilder.createColumn(PostgresJdbcDeployDatabaseMutationBuilder.scala:165)\n\tat com.prisma.deploy.connector.jdbc.database.CreateColumnHelper$.withIndexIfNecessary(ColumnMutactionInterpreters.scala:156)\n\tat com.prisma.deploy.connector.jdbc.database.CreateColumnInterpreter.execute(ColumnMutactionInterpreters.scala:14)\n\tat com.prisma.deploy.connector.jdbc.database.JdbcDeployMutactionExecutor.execute(JdbcDeployMutactionExecutor.scala:41)\n\tat com.prisma.deploy.migration.migrator.MigrationApplierImpl.executeClientMutaction(MigrationApplier.scala:119)\n\tat com.prisma.deploy.migration.migrator.MigrationApplierImpl.$anonfun$applyStep$2(MigrationApplier.scala:106)\n\tat scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)\n\tat scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)\n\tat scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)\n\tat akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)\n\tat akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)\n\tat scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)\n\tat scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)\n\tat akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)\n\tat akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)\n\tat akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)\n\tat akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)\n\tat akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)\n\tat akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)\n\tat akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)\n' ],
  client      revision: 71,
  client      status: 'ROLLING_BACK' } } +68ms

Applying changes... 3.6s
Error: The Migration failed and has not been performed. This is very likely not a transient issue.
java.lang.RuntimeException: MigrationValue method should only be called on scalar fields.
	at scala.sys.package$.error(package.scala:26)
	at com.prisma.deploy.connector.MigrationValueGenerator.migrationValueForField(MigrationValueGenerator.scala:18)
	at com.prisma.deploy.connector.MigrationValueGenerator.migrationValueForField$(MigrationValueGenerator.scala:9)
	at com.prisma.deploy.connector.postgres.database.PostgresJdbcDeployDatabaseMutationBuilder.migrationValueForField(PostgresJdbcDeployDatabaseMutationBuilder.scala:20)
	at com.prisma.deploy.connector.postgres.database.PostgresJdbcDeployDatabaseMutationBuilder.createColumn(PostgresJdbcDeployDatabaseMutationBuilder.scala:165)
	at com.prisma.deploy.connector.jdbc.database.CreateColumnHelper$.withIndexIfNecessary(ColumnMutactionInterpreters.scala:156)
	at com.prisma.deploy.connector.jdbc.database.CreateColumnInterpreter.execute(ColumnMutactionInterpreters.scala:14)
	at com.prisma.deploy.connector.jdbc.database.JdbcDeployMutactionExecutor.execute(JdbcDeployMutactionExecutor.scala:41)
	at com.prisma.deploy.migration.migrator.MigrationApplierImpl.executeClientMutaction(MigrationApplier.scala:119)
	at com.prisma.deploy.migration.migrator.MigrationApplierImpl.$anonfun$applyStep$2(MigrationApplier.scala:106)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

    at Deploy.<anonymous> (/Users/kenono/.nvm/versions/node/v10.13.0/lib/node_modules/prisma/node_modules/prisma-cli-core/src/commands/deploy/deploy.ts:280:17)
    at step (/Users/kenono/.nvm/versions/node/v10.13.0/lib/node_modules/prisma/node_modules/prisma-cli-core/dist/commands/deploy/deploy.js:45:23)
    at Object.next (/Users/kenono/.nvm/versions/node/v10.13.0/lib/node_modules/prisma/node_modules/prisma-cli-core/dist/commands/deploy/deploy.js:26:53)
    at fulfilled (/Users/kenono/.nvm/versions/node/v10.13.0/lib/node_modules/prisma/node_modules/prisma-cli-core/dist/commands/deploy/deploy.js:17:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  util timed out +0ms
  output Exiting with code: 0 +0ms
````

**Comment by divyenduz** [comment]
@kokokenada : Can you please share more information like your datamodel? Prisma server version etc?  Maybe a minimal reproduction repository that would help us understand the issue better, thanks 🙏

**Comment by kokokenada** [comment]
I upgraded to 1.30.1 and I was able to do the deploy, so the problem I encountered is no longer present.
