### ISSUE TITLE
Database "prisma" already exists

### ISSUE THREAD

**Issue by fineline** [prisma/datamodel-v1.1-feedback#12]
When I attempt to upgrade to `prisma@beta` to try out the data mode 1.1, I continually get the following error. I have done `docker system prune`, `docker volume prune` and removed all images and started from scratch with the provided docker-compose settings. Where is it finding this existing `prisma` database?

```
Creating network "test-prisma_default" with the default driver
Creating volume "test-prisma_postgres" with default driver
Creating test-prisma_prisma_1   ... done
Creating test-prisma_postgres_1 ... done
Attaching to test-prisma_prisma_1, test-prisma_postgres_1
postgres_1  | The files belonging to this database system will be owned by user "postgres".
postgres_1  | This user must also own the server process.
postgres_1  | 
postgres_1  | The database cluster will be initialized with locale "en_US.utf8".
postgres_1  | The default database encoding has accordingly been set to "UTF8".
postgres_1  | The default text search configuration will be set to "english".
postgres_1  | 
postgres_1  | Data page checksums are disabled.
postgres_1  | 
postgres_1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgres_1  | creating subdirectories ... ok
postgres_1  | selecting default max_connections ... 100
postgres_1  | selecting default shared_buffers ... 128MB
postgres_1  | selecting dynamic shared memory implementation ... posix
postgres_1  | creating configuration files ... ok
postgres_1  | running bootstrap script ... ok
postgres_1  | performing post-bootstrap initialization ... ok
postgres_1  | syncing data to disk ... ok
postgres_1  | 
postgres_1  | Success. You can now start the database server using:
postgres_1  | 
postgres_1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgres_1  | 
postgres_1  | 
postgres_1  | WARNING: enabling "trust" authentication for local connections
postgres_1  | You can change this by editing pg_hba.conf or using the option -A, or
postgres_1  | --auth-local and --auth-host, the next time you run initdb.
postgres_1  | waiting for server to start....2019-03-30 11:36:45.699 UTC [43] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2019-03-30 11:36:45.724 UTC [44] LOG:  database system was shut down at 2019-03-30 11:36:45 UTC
postgres_1  | 2019-03-30 11:36:45.731 UTC [43] LOG:  database system is ready to accept connections
postgres_1  |  done
postgres_1  | server started
postgres_1  | CREATE DATABASE
postgres_1  | 
postgres_1  | 
postgres_1  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
postgres_1  | 
postgres_1  | waiting for server to shut down....2019-03-30 11:36:46.174 UTC [43] LOG:  received fast shutdown request
postgres_1  | 2019-03-30 11:36:46.177 UTC [43] LOG:  aborting any active transactions
postgres_1  | 2019-03-30 11:36:46.180 UTC [43] LOG:  background worker "logical replication launcher" (PID 50) exited with exit code 1
postgres_1  | 2019-03-30 11:36:46.181 UTC [45] LOG:  shutting down
postgres_1  | 2019-03-30 11:36:46.197 UTC [43] LOG:  database system is shut down
postgres_1  |  done
postgres_1  | server stopped
postgres_1  | 
postgres_1  | PostgreSQL init process complete; ready for start up.
postgres_1  | 
postgres_1  | 2019-03-30 11:36:46.288 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1  | 2019-03-30 11:36:46.289 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1  | 2019-03-30 11:36:46.293 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
prisma_1    | No log level set, defaulting to INFO.
postgres_1  | 2019-03-30 11:36:46.308 UTC [61] LOG:  database system was shut down at 2019-03-30 11:36:46 UTC
postgres_1  | 2019-03-30 11:36:46.317 UTC [1] LOG:  database system is ready to accept connections
postgres_1  | 2019-03-30 11:36:46.415 UTC [69] ERROR:  database "prisma" already exists
postgres_1  | 2019-03-30 11:36:46.415 UTC [69] STATEMENT:  CREATE DATABASE "prisma"
prisma_1    | [INFO] Obtaining exclusive agent lock...
prisma_1    | [INFO] Initializing workers...
prisma_1    | [INFO] Obtaining exclusive agent lock... Successful.
prisma_1    | [INFO] Successfully started 1 workers.
prisma_1    | [INFO] Deployment worker initialization complete.
prisma_1    | Server running on :4466
prisma_1    | Trying (via loadLibrary) jnidispatch
prisma_1    | Looking in classpath from sun.misc.Launcher$AppClassLoader@7852e922 for /com/sun/jna/linux-x86-64/libjnidispatch.so
prisma_1    | Found library resource at jar:file:/app/lib/net.java.dev.jna.jna-4.5.2.jar!/com/sun/jna/linux-x86-64/libjnidispatch.so
prisma_1    | Trying /tmp/jna-3506402/jna371727308653010446.tmp
prisma_1    | Found jnidispatch at /tmp/jna-3506402/jna371727308653010446.tmp
prisma_1    | Looking for library 'jwt_native'
prisma_1    | Adding paths from jna.library.path: null
prisma_1    | Trying libjwt_native.so
prisma_1    | Adding system paths: [/lib64, /usr/lib, /lib]
prisma_1    | Trying /lib/libjwt_native.so
prisma_1    | Found library 'jwt_native' at /lib/libjwt_native.so
prisma_1    | java.lang.RuntimeException: ProjectHelper: Could not resolve project with id: default$default
prisma_1    |   at scala.sys.package$.error(package.scala:26)
prisma_1    |   at com.prisma.subscriptions.helpers.ProjectHelper$.$anonfun$resolveProject$1(ProjectHelper.scala:13)
prisma_1    |   at scala.util.Success.$anonfun$map$1(Try.scala:251)
prisma_1    |   at scala.util.Success.map(Try.scala:209)
prisma_1    |   at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
prisma_1    |   at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
prisma_1    |   at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
prisma_1    |   at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
prisma_1    |   at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
prisma_1    |   at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
prisma_1    |   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
prisma_1    |   at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
prisma_1    |   at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
prisma_1    |   at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
prisma_1    |   at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
prisma_1    |   at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
prisma_1    |   at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
prisma_1    |   at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
prisma_1    |   at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```

**Comment by fineline** [comment]
I resolved this as follows:

* `docker-compose up`
* `docker ps -a`
* Check ID of the prisma container
* `docker container rm ` then first 3 chars of prisma container id

So at this stage, only the postgres container is running - I have also mapped port 5432 on that container to a local port so I can access it via pgAdmin

* In pgAdmin, delete the database "prisma" (Can't do this while prisma container is running)
* `docker-compose down`
* `docker-compose up`

From that point all runs well.

So I guess the problem was related to

1. The previous database I had, from my old version of prisma, was somehow not compatible with teh beta version?
2. I though `docker volume prune` that I was trying previously would have deleted the postgres data. Seems I need to do some further reading to improve my understanding of docker volumes and the lifetimes of their backing storage.
